#!/bin/bash

# set pointer
xsetroot -cursor_name left_ptr
# run key daemon
sxhkd &

bspc config border_width	2
bspc config window_gap		0

bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1 # alt-click to move via mouse
bspc config borderless_monocle   true

bspc config automatic_scheme	spiral
