#!/usr/bin/env bash
# Activate a sketchybar variant and apply manifest feature flags.

set -euo pipefail

# shellcheck source=scripts/lib/common.sh
source "$(dirname "$0")/lib/common.sh"
# shellcheck source=scripts/lib/manifest.sh
source "$(dirname "$0")/lib/manifest.sh"

export DOTFILES_PROFILE="${DOTFILES_PROFILE:-work.mac}"

VARIANT=""
LAYOUT=""
SPOTIFY=""
FROM_MANIFEST=0
SAVE_LOCAL=0

usage() {
  cat <<'EOF'
Usage: sketchybar-switch.sh [options]

  --from-manifest          Use profiles/<DOTFILES_PROFILE>/manifest.toml (default in bootstrap)
  --variant <felix|neuton|oxgr>
  --layout <laptop|desktop|default>   Neuton layout only
  --spotify <on|off>                  Override spotify_widget feature
  --save                              Write overrides to ~/.config/dotfiles/local.toml (gitignored)

Examples:
  sketchybar-switch.sh --from-manifest
  sketchybar-switch.sh --variant felix --spotify off
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-manifest) FROM_MANIFEST=1; shift ;;
    --variant) VARIANT="$2"; shift 2 ;;
    --layout) LAYOUT="$2"; shift 2 ;;
    --spotify)
      case "$2" in
        on|true|1) SPOTIFY=1 ;;
        off|false|0) SPOTIFY=0 ;;
        *) die "invalid --spotify value: $2" ;;
      esac
      shift 2
      ;;
    --save) SAVE_LOCAL=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

if [[ "$FROM_MANIFEST" -eq 1 ]]; then
  VARIANT="${VARIANT:-$(manifest_get sketchybar.variant)}"
  LAYOUT="${LAYOUT:-$(manifest_get sketchybar.neuton_layout)}"
  if [[ -z "$SPOTIFY" ]]; then
    if manifest_get sketchybar.features.spotify_widget; then
      SPOTIFY=1
    else
      SPOTIFY=0
    fi
  fi
fi

[[ -n "$VARIANT" ]] || die "variant required (use --variant or --from-manifest)"
[[ -n "$SPOTIFY" ]] || SPOTIFY=0

MOD="sketchybar-$VARIANT"
[[ -d "$DOTFILES_ROOT/modules/$MOD" ]] || die "unknown variant module: $MOD"

ACTIVE_FILE="$DOTFILES_STATE_DIR/active-sketchybar"
PREV=""
[[ -f "$ACTIVE_FILE" ]] && PREV="$(cat "$ACTIVE_FILE")"

if [[ -n "$PREV" && "$PREV" != "$MOD" ]]; then
  log "unstowing previous sketchybar: $PREV"
  "$DOTFILES_ROOT/scripts/stow-module.sh" -D "$PREV" || true
fi

log "stowing sketchybar variant: $MOD (spotify=$([[ $SPOTIFY -eq 1 ]] && echo on || echo off))"
"$DOTFILES_ROOT/scripts/stow-module.sh" -R "$MOD"

CONFIG="$HOME/.config/sketchybar"
FEATURES="$DOTFILES_ROOT/modules/sketchybar-neuton/features"

_apply_neuton_rc() {
  local layout="${LAYOUT:-laptop}"
  local base inc out="$CONFIG/sketchybarrc"
  local neuton_src="$DOTFILES_ROOT/modules/sketchybar-neuton/home/.config/sketchybar"

  case "$layout" in
    laptop)
      base="$FEATURES/sketchybarrc-laptop.base"
      inc="$FEATURES/spotify-laptop.inc"
      ;;
    desktop)
      base="$FEATURES/sketchybarrc-desktop.base"
      inc="$FEATURES/spotify-desktop.inc"
      ;;
    default)
      cp "$CONFIG/sketchybarrc" "$out.bak" 2>/dev/null || true
      cp "$neuton_src/sketchybarrc" "$out"
      warn "neuton default layout: use laptop/desktop for manifest spotify_widget control"
      return
      ;;
    *) die "unknown layout: $layout" ;;
  esac

  if [[ "$SPOTIFY" -eq 1 ]]; then
    awk -v frag="$inc" '
      /# __SPOTIFY_FRAGMENT__/ {
        while ((getline line < frag) > 0) print line
        close(frag)
        next
      }
      { print }
    ' "$base" >"$out"
  else
    awk '/# __SPOTIFY_FRAGMENT__/ { next } { print }' "$base" >"$out"
  fi
  chmod +x "$out"
}

_apply_felix_spotify() {
  local rc="$CONFIG/sketchybarrc"
  local felix_src="$DOTFILES_ROOT/modules/sketchybar-felix/home/.config/sketchybar"
  if [[ "$SPOTIFY" -eq 1 ]]; then
    cp "$felix_src/sketchybarrc" "$rc"
    chmod +x "$rc"
  else
    grep -v 'source "$ITEM_DIR/spotify.sh"' "$felix_src/sketchybarrc" >"$rc"
    chmod +x "$rc"
    cp "$DOTFILES_ROOT/modules/sketchybar-felix/features/spotify.disabled.sh" \
      "$CONFIG/items/spotify.sh"
  fi
}

case "$VARIANT" in
  neuton) _apply_neuton_rc ;;
  felix) _apply_felix_spotify ;;
  oxgr)
    log "oxgr has no spotify widget; using stock sketchybarrc"
    ;;
  *) die "unsupported variant: $VARIANT" ;;
esac

printf '%s\n' "$MOD" >"$ACTIVE_FILE"

if command -v sketchybar >/dev/null 2>&1; then
  sketchybar --reload 2>/dev/null || brew services restart sketchybar 2>/dev/null || true
fi

if [[ "$SAVE_LOCAL" -eq 1 ]]; then
  LOCAL_DIR="$HOME/.config/dotfiles"
  mkdir -p "$LOCAL_DIR"
  cat >"$LOCAL_DIR/local.toml" <<EOF
# Generated by sketchybar-switch.sh — not in git
[sketchybar]
variant = "$VARIANT"
neuton_layout = "${LAYOUT:-laptop}"

[sketchybar.features]
spotify_widget = $([[ "$SPOTIFY" -eq 1 ]] && echo true || echo false)
EOF
  log "saved local overrides to $LOCAL_DIR/local.toml"
fi

log "active sketchybar: $MOD"
